apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    env: demo
spec:
  template:
    metadata:
      name: nginx-demo
      labels:
        env: demo
    spec:
      containers:
      - image: nginx
        name: nginx-container
  replicas: 3
  selector:
    matchLabels:
      env: demo
