apiVersion: v1
kind: Pod
metadata:
  name: nginx-dev
  labels:
    environment: dev
    app: nginx-hzln
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  nodeName: hzln-cluster-kind-worker3
