apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx-aff-pref
spec:
  containers:
  - image: nginx
    name: nginx-aff-pref
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: disktype
            operator: In
            values:
            - hdd
      - weight: 50
        preference:
          matchExpressions:
          - key: on-demand
            operator: In
            values:
            - common
